<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Contact | VetTech Connect</title>
</head>
<body>
    <h1>Contact Us</h1>
    <p>This page is under construction. For now, please reach out via email or social media.</p>
    <a href="index.html">Return to Home</a>
</body>
</html>


