<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Careers | VetTech Connect</title>
</head>
<body>
    <h1>Careers</h1>
    <p>This section is currently under development. Career listings and guidance will be available soon.</p>
    <a href="index.html">Return to Home</a>
</body>
</html>

