theme: minima
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>VetTech Connect | Home</title>
    <meta name="description" content="VetTech Connect helps U.S. military veterans transition into the IT sector.">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        body { font-family: Arial, sans-serif; margin: 0; background-color: #f4f4f4; }
        header { background-color: #003366; color: white; padding: 20px 0; text-align: center; }
        nav { background-color: #00509e; padding: 10px 0; text-align: center; }
        nav a { color: white; margin: 0 15px; text-decoration: none; font-weight: bold; }
        nav a:hover { text-decoration: underline; }
        main { max-width: 900px; margin: 40px auto; background: white; padding: 20px; box-shadow: 0 0 10px rgba(0,0,0,0.1); }
        footer { background-color: #003366; color: white; text-align: center; padding: 15px; position: fixed; width: 100%; bottom: 0; }
    </style>
</head>
<body>

<header>
    <h1>VetTech Connect</h1>
    <p>Bridging Veterans to Tech Careers</p>
</header>

<nav>
    <a href="index.html">Home</a>
    <a href="about.html">About Us</a>
    <a href="resources.html">Resources</a>
    <a href="careers.html">Careers</a>
    <a href="contact.html">Contact</a>
</nav>

<main>
    <h2>Welcome to VetTech Connect</h2>
    <p>
        VetTech Connect is a mission-driven digital platform dedicated to supporting U.S. military veterans in transitioning from service to careers in information technology. 
        We serve as a one-stop-shop for guidance, training, and opportunities in the evolving tech industry.
    </p>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</p>
</main>

<footer>
    &copy; 2025 VetTech Connect. All Rights Reserved.
</footer>

</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About Us | VetTech Connect</title>
</head>
<body>
    <h1>About Us</h1>
    <p>This page is currently under construction. Please check back soon!</p>
    <a href="index.html">Return to Home</a>
</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Resources | VetTech Connect</title>
</head>
<body>
    <h1>Resources</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum in porta justo. Suspendisse potenti.</p>
    <a href="index.html">Return to Home</a>
</body>
</html>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Careers | VetTech Connect</title>
</head>
<body>
    <h1>Careers</h1>
    <p>This section is currently under development. Career listings and guidance will be available soon.</p>
    <a href="index.html">Return to Home</a>
</body>
</html>
